services:
  - type: web
    name: apptrack-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: apptrack-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: apptrack-db
    databaseName: apptrack
    user: apptrack_user
    plan: free
